1. Corpus: combination of all words
2. Vocabulary: Unique words which makes the corpus
3. Document: Individual set
4. Word: 

In [1]:
#One hot encoding
#ismein word ko V dimension mein convert krte hain
#easy hai yeh aur intuitive hai, lekin isme sparsity hai--> bss ek 1 hai baaki 0 aur isse overfitting hoti hai
#zyada  word hoega agr toh shape alag ho jaaega aur fixed size nhi milega jisse ML algo kaam nhi krengi
#ab agr input mein alag hee word aagya(OOV)
#No capturing of semantic meaning -->zyada dissimilar words bhi equidistant bnn jaate hain


In [2]:
#Bag of Words --> isme uss word ko dekho current document mein kitni baar aarhe hain
import numpy as np
import pandas as pd



In [3]:
df=pd.DataFrame({'text':['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'],'output':[1,1,0,0]})

In [4]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [6]:
bow=cv.fit_transform(df['text'])

In [7]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [8]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [ ]:
cv.transform(["campusx watch and write comment of campusx"]).toarray() #dekho ismein OOV nahi hua, out of vocab
#binary=true se kya hoega agr kisi ki frequency mein 1 se zyada hai toh voh agr 1 se zyada occurrence hoega toh use 1 bna dega

# it is simple and intutive 
# yhan pr fixed size hee rhega
# OOV bhi krliya solve
# thora sa semantic meaning capture krta hai -DOUBT
# Lekin sparsity hai yahan
# ab yaha n tum oov ko ignore krde rhe ho
# yahan ordering ko bhool jaate hain jisse kaafi baar meaning change ho jata hai
# ek sentence mein NOT nahi hai dusre mein sirf ek NOT agya toh bow sochega almost same meaning hai but aisa nahi hai




array([[2, 1, 0, 1, 1]])